function createContainerStatisticsFraudSumMain() {
    createElementDivAnaDivChild(containerGameFiledStatisticsFraudParts, containerGameFiledStatisticsFraudBest, containerGameFiledStatisticsFraudBestParts);
    setElementClassNameById(containerGameFiledStatisticsFraudBestParts, containerGameFiledCommonParts);
}

function createContainerStatisticsFraudMain(containerGameFiledStatisticsFraudParts, containerGameFiledStatisticsFraudGamePlay, fraudUpdate, gameFiledStatisticsFraudGamePlay, commonGameFiledDisplay) {
    createElementDivWithIdAndSetClassName(containerGameFiledStatisticsFraudParts, containerGameFiledStatisticsFraudGamePlay, fraudUpdate);
    createElementDivWithIdAndSetClassName(containerGameFiledStatisticsFraudGamePlay, gameFiledStatisticsFraudGamePlay, commonGameFiledDisplay);
}

function createContainerStatisticsFraudSumUpdate() {
    createContainerStatisticsFraudMain(containerGameFiledStatisticsFraudBestParts, containerGameFiledStatisticsFraudBestGamePlay, fraudCountRoundUpdateSumNumber, gameFiledStatisticsFraudBestGamePlay, commonGameFiledDisplay);
    createElementDivWithIdAndSetClassName(gameFiledStatisticsFraudBestGamePlay, statisticsFraudBestGamePlay, commonGamePlayTextUpdate);
    setElementClassNamedAndText(statisticsFraudBestGamePlay, statisticsFraudBestUpdateNumber, statisticsFraudBestGamePlayDisplay);
}

function createContainerStatisticsFraudSumTextStatic() {
    createContainerStatisticsFraudMain(containerGameFiledStatisticsFraudBestParts, containerGameFiledStatisticsFraudBestText, containerGameFiledCommonStaticText, gameFiledStatisticsFraudBestText, commonGameFiledDisplay);
    createElementDivWithIdAndSetClassName(gameFiledStatisticsFraudBestText, statisticsFraudBestText, commonStaticText);
    setElementClassNameSameAsIdAndSetText(statisticsFraudBestText, statisticsFraudBestTextDisplay);
}

function createContainerStatisticsFraudSum() {
    createContainerStatisticsFraudSumMain();
    createContainerStatisticsFraudSumUpdate()
    createContainerStatisticsFraudSumTextStatic();
}

function createContainerStatisticsFraudRoundUpdate() {
    createElementDivWithTheSameIdAndClassName(containerGameFiledStatisticsFraudParts, containerGameFiledStatisticsFraudCount);
    createElementDivWithIdAndSetClassName(containerGameFiledStatisticsFraudCount, containerGameFiledStatisticsFraudCountParts, containerGameFiledCommonParts);
    createElementDiv(containerGameFiledStatisticsFraudCountParts, containerGameFiledStatisticsFraudCountGamePlay);
    createElementDiv(containerGameFiledStatisticsFraudCountParts, containerGameFiledStatisticsFraudCountText);
    createContainerStatisticsFraudMain(containerGameFiledStatisticsFraudCountText, gameFiledStatisticsFraudCountText, commonGameFiledDisplay, statisticsFraudCountText, commonStaticText);
    setElementClassNameSameAsIdAndSetText(statisticsFraudCountText, statisticsFraudCountTextDisplay);
}

function createGameFieldStatisticsFraud() {
    createElementDivWithTheSameIdAndClassName(containerGameFiledStatisticsFraud, containerGameFiledStatisticsFraudParts);
    createContainerStatisticsFraudSum();
    createContainerStatisticsFraudRoundUpdate();
    createContainerStatisticsFraudCountPerRound();
}