export const containerMenuGameConfiguration = "containerMenuGameConfiguration";
export const containerMenuGameConfigurationParts = "containerMenuGameConfigurationParts";
export const menuGameConfigurationDisplay = "menuGameConfigurationDisplay";
export const containerMenuGameConfigurationText = "containerMenuGameConfigurationText";
export const menuGameConfigurationText = "menuGameConfigurationText";
export const menuGameConfigurationButton = "menuGameConfigurationButton";
export const menuGameConfigurationButtonCurrentNumber = "menuGameConfigurationButtonCurrentNumber";
export const functionNameOnclickSetConfigurationClickNumber = "setConfigurationClickNumber";
export const menuGameConfigurationButtonClickNumberPrefix = "menuGameConfigurationButtonClickNumber-";
export const menuGameConfigurationButtonClickNumberGameOn = "menuGameConfigurationButtonClickNumberGameOn";
export const menuGameConfigurationButtonChosenNumber = "menuGameConfigurationButtonChosenNumber";
export const menuGameConfigurationTextDisplay = "<i class=\"fa-solid fa-screwdriver-wrench\"></i>";
export const containerMenuGameConfigurationGameKind = "containerMenuGameConfigurationGameKind";
export const containerMenuGameConfigurationClickNumber = "containerMenuGameConfigurationClickNumber";
export const containerMenuGameConfigurationClickNumberParts = "containerMenuGameConfigurationClickNumberParts";
export const containerMenuGameConfigurationClickNumberRow0 = "containerMenuGameConfigurationClickNumber-row0";
export const containerMenuGameConfigurationClickNumberPartsRow0 = "containerMenuGameConfigurationClickNumberParts-row0";
export const containerMenuGameConfigurationClickNumberRow1 = "containerMenuGameConfigurationClickNumber-row1";
export const containerMenuGameConfigurationClickNumberPartsRow1 = "containerMenuGameConfigurationClickNumberParts-row1";
export const containerMenuGameConfigurationClickNumberPartsRow = "containerMenuGameConfigurationClickNumberParts-row";
export const menuGameConfigurationClickNumberTextDisplay = "<i class=\"fa-solid fa-computer-mouse\"></i> &nbsp &nbsp"
export const containerGameConfigurationRoundNumberPrefix = "containerGameConfigurationRoundNumber-";